apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runtime-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - runtime: pipeline1-runtime
        clusterURL: https://192.168.0.243:31543
  template:
    metadata:
      name: '{{runtime}}'
      namespace: argocd
    spec:
      project: demo-vcluster
      source:
        repoURL: https://github.com/liujunhong5891/demo-pipeline-argoevents-tekton.git
        targetRevision: HEAD
        path: runtimes/{{runtime}}
      destination:
        server: '{{clusterURL}}'
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
